#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER "$API_DB_USER" WITH PASSWORD '$API_DB_PASSWORD';
  CREATE DATABASE "$API_DB_NAME" OWNER "$API_DB_USER";
  CREATE DATABASE "${API_DB_NAME}-test" OWNER "$API_DB_USER";
EOSQL
